// Generated by CodiumAI

// script.test.js

// Import the source file where showWeatherData is defined
const { showWeatherData } = require('./script');


describe('showWeatherData', () => {
  // Function displays current weather data in HTML format
  it('displays current weather data in HTML format when data object is provided', () => {
    const data = {
      current: {
        humidity: 50,
        pressure: 1012,
        sunrise: 1623456789,
        sunset: 1623512345,
        wind_speed: 10
      },
      timezone: "America/New_York",
      lat: 40.7128,
      lon: -74.0060,
      daily: [
        {
          dt: 1623456789,
          temp: {
            night: 20,
            day: 25
          },
          weather: [
            {
              icon: "01d"
            }
          ]
        }
      ]
    };

    showWeatherData(data);

    expect(timeZone.innerHTML).toBe("America/New_York");
    expect(country.innerHTML).toBe("40.7128N -74.0060E");
    expect(currentWeatherItemsElement.innerHTML).toContain("Humidity");
    expect(currentWeatherItemsElement.innerHTML).toContain("Pressure");
    expect(currentWeatherItemsElement.innerHTML).toContain("Wind Speed");
    expect(currentWeatherItemsElement.innerHTML).toContain("Sunrise");
    expect(currentWeatherItemsElement.innerHTML).toContain("Sunset");
    expect(currentTempElement.innerHTML).toContain("Night - 20°C");
    expect(currentTempElement.innerHTML).toContain("Day - 25°C");
    expect(weatherForecastElement.innerHTML).toContain("Mon");
    expect(weatherForecastElement.innerHTML).toContain("Night - 20°C");
    expect(weatherForecastElement.innerHTML).toContain("Day - 25°C");
  });

  // Function displays weather forecast data in HTML format
  it('displays weather forecast data in HTML format when data object is provided', () => {
    const data = {
      current: {
        humidity: 50,
        pressure: 1012,
        sunrise: 1623456789,
        sunset: 1623512345,
        wind_speed: 10
      },
      timezone: "America/New_York",
      lat: 40.7128,
      lon: -74.0060,
      daily: [
        {
          dt: 1623456789,
          temp: {
            night: 20,
            day: 25
          },
          weather: [
            {
              icon: "01d"
            }
          ]
        },
        {
          dt: 1623543210,
          temp: {
            night: 18,
            day: 23
          },
          weather: [
            {
              icon: "02d"
            }
          ]
        }
      ]
    };

    showWeatherData(data);

    expect(weatherForecastElement.innerHTML).toContain("Tue");
    expect(weatherForecastElement.innerHTML).toContain("Night - 18°C");
    expect(weatherForecastElement.innerHTML).toContain("Day - 23°C");
  });

  // Function correctly formats and displays sunrise and sunset times
  it('correctly formats and displays sunrise and sunset times when data object is provided', () => {
    const data = {
      current: {
        humidity: 50,
        pressure: 1012,
        sunrise: 1623456789,
        sunset: 1623512345,
        wind_speed: 10
      },
      timezone: "America/New_York",
      lat: 40.7128,
      lon: -74.0060,
      daily: [
        {
          dt: 1623456789,
          temp: {
            night: 20,
            day: 25
          },
          weather: [
            {
              icon: "01d"
            }
          ]
        }
      ]
    };

    showWeatherData(data);

    expect(currentWeatherItemsElement.innerHTML).toContain("Sunrise");
    expect(currentWeatherItemsElement.innerHTML).toContain("Sunset");
    expect(currentWeatherItemsElement.innerHTML).toContain("12:13 PM");
    expect(currentWeatherItemsElement.innerHTML).toContain("10:25 PM");
  });

  // Data object is empty
  it('does not display any weather data when data object is empty', () => {
    const data = {};

    showWeatherData(data);

    expect(timeZone.innerHTML).toBe("");
    expect(country.innerHTML).toBe("");
    expect(currentWeatherItemsElement.innerHTML).toBe("");
    expect(currentTempElement.innerHTML).toBe("");
    expect(weatherForecastElement.innerHTML).toBe("");
  });

  // Data object is missing required properties
  it('does not display any weather data when data object is missing required properties', () => {
    const data = {
      current: {
        humidity: 50,
        pressure: 1012,
        sunrise: 1623456789,
        sunset: 1623512345,
        wind_speed: 10
      },
      daily: [
        {
          dt: 1623456789,
          temp: {
            night: 20,
            day: 25
          },
          weather: [
            {
              icon: "01d"
            }
          ]
        }
      ]
    };

    showWeatherData(data);

    expect(timeZone.innerHTML).toBe("");
    expect(country.innerHTML).toBe("");
    expect(currentWeatherItemsElement.innerHTML).toBe("");
    expect(currentTempElement.innerHTML).toBe("");
    expect(weatherForecastElement.innerHTML).toBe("");
  });

  // Data object has incorrect property types
  it('does not display any weather data when data object has incorrect property types', () => {
    const data = {
      current: {
        humidity: "50",
        pressure: 1012,
        sunrise: 1623456789,
        sunset: 1623512345,
        wind_speed: 10
      },
      timezone: "America/New_York",
      lat: "40.7128",
      lon: -74.0060,
      daily: [
        {
          dt: 1623456789,
          temp: {
            night: "20",
            day: 25
          },
          weather: [
            {
              icon: "01d"
            }
          ]
        }
      ]
    };

    showWeatherData(data);

    expect(timeZone.innerHTML).toBe("");
    expect(country.innerHTML).toBe("");
    expect(currentWeatherItemsElement.innerHTML).toBe("");
    expect(currentTempElement.innerHTML).toBe("");
    expect(weatherForecastElement.innerHTML).toBe("");
  });
});

